# Generated by Django 4.0 on 2023-11-08 13:16

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPost',
            fields=[
                ('docpost_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('videoUrl', embed_video.fields.EmbedVideoField()),
                ('head0', models.CharField(default='', max_length=500)),
                ('chead0', models.CharField(default='', max_length=500)),
                ('para0', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=500)),
                ('chead1', models.CharField(default='', max_length=500)),
                ('para1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=500)),
                ('chead2', models.CharField(default='', max_length=500)),
                ('para2', models.CharField(default='', max_length=5000)),
                ('head3', models.CharField(default='', max_length=500)),
                ('chead3', models.CharField(default='', max_length=500)),
                ('para3', models.CharField(default='', max_length=5000)),
                ('ccode', models.CharField(default='', max_length=3000)),
                ('cppcode', models.CharField(default='', max_length=3000)),
                ('pycode', models.CharField(default='', max_length=3000)),
                ('javacode', models.CharField(default='', max_length=3000)),
                ('images', models.ImageField(default='', upload_to='documentation/images')),
                ('pub_date', models.DateField(max_length=30)),
            ],
        ),
    ]
