# Generated by Django 5.0.1 on 2024-01-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_documentpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpost',
            old_name='images',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='ccode',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='chead3',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='cppcode',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='head3',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='javacode',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='para0',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='para1',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='para2',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='para3',
        ),
        migrations.RemoveField(
            model_name='documentpost',
            name='pycode',
        ),
        migrations.AlterField(
            model_name='documentpost',
            name='chead0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='documentpost',
            name='chead1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='documentpost',
            name='chead2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
