# Generated by Django 4.0 on 2023-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAVApp', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedbackMsg',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
