# Generated by Django 4.0 on 2023-11-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GAVApp', '0005_feedback_feedbackmsg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
