# Generated by Django 5.0.1 on 2024-03-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAVApp', '0006_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
